### DISCUSSION TITLE
How to run the app on Ubuntu server 20.04

### DISCUSSION THREAD

**Discussion by edison23** [photoview/photoview#158] [Q&A and Troubleshooting] [answered]
This question is basically an ask to supplement the documentation of PhotoView which is very brief, let's say. I have no experience with Docker apps so that's probably the reason I'm lost.

**My problem:** I installed `docker.io` and `docker-compose` and went thru the [Getting started - Setup with Docker](https://github.com/photoview/photoview#getting-started---setup-with-docker) in the Readme. No errors encountered but when I finished and navigated to the directory whither I placed PhotoView, I got only the default Apache directory listing. It doesn't seem to be a problem of permissions as Apache never gave me the usual 403 error it throws in these situations. 

Could you please help me figure out what I'm missing? Thank you. 

I'm running Ubuntu server 20.04 on 64bit machine:
`Linux aperture 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Here are commands that got me to the aforementioned state:

1. `$ sudo apt install docker.io` to install docker
1. `$ sudo systemctl enable --now docker.service` to enable docker service and start it
1. `$ sudo usermod -aG docker edison23` to add myself to the docker group (I logged out and back in after that)
1. `$ docker run hello-world` to try if docker works, everything seems fine
1. `$ sudo apt install docker-compose` to install docker-compose
1. `$ git clone` of this repo into a directory under root of my website
1. copied `docker-compose.example.yml` to `docker-compose.yml` and updated it to match DB, user and psw I created in MySQL, and the path I placed PhotoView to (directory `pv` right under root of my domain) which is directory `exampleorg` in this slightly file below).
1. `$ docker-compose up -d` to start PhotoView. Everything seemed fine, no error occured. But when I navigate to https://example.org/pv, all I see is directory listing of the directory.

And here's my docker-compose.yml (stripped of sensitive info like passwords, Mapbox token, or domain, of course):

```
version: "3"

services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=USER-FOR-PHOTOVIEW
      - MYSQL_PASSWORD=PSW-FOR-THE-USER
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - db_data:/var/lib/mysql

  photoview:
    image: viktorstrate/photoview:1
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - db

    environment:
      - MYSQL_URL=photoview:photo-secret@tcp(db)/photoview
      - API_LISTEN_IP=photoview
      - API_LISTEN_PORT=80
      - PHOTO_CACHE=/app/cache

      # Change This: The publicly exposed url
      # For example if the server is available from the domain example.com,
      # change this value to http://example.com/
      - PUBLIC_ENDPOINT=https://example.org/pv/

      # Optional: To enable map related features, you need to create a mapbox token.
      # A token can be generated for free here https://account.mapbox.com/access-tokens/
      # It's a good idea to limit the scope of the token to your own domain, to prevent others from using it.
      - MAPBOX_TOKEN=loremipsumdolorsitamet

    volumes:
      - api_cache:/app/cache

      # Change this to the directory where your photos are located on your server.
      # If the photos are located at `/home/user/photos`, then change this value
      # to the following: `/home/user/photos:/photos:ro`.
      # You can mount multiple paths, if your photos are spread across multiple directories.
      #- ./photos_path:/photos:ro
      - /mydrive/www/exampleorg/mobilephotos:/mobilephotos:ro

volumes:
  db_data:
  api_cache:
```

Thanks for your help

**Comment by viktorstrate** [comment]
Hi @edison23 
Thank you for your interest in the project, and the detailed explaination.

Photoview doesn't use Apache at all, so you probably hit another server.

Your configuration looks ok, it should be accessible from `localhost:8000`.
I see that you use your own domain, and wan't to access Photoview from `/pv`, can you explain how you have configured that? You would have to use a reverse proxy to do so, maybe Apache is used for that, if so could you post your configuration for that?

**Comment by edison23** [comment, marked as answer]
Hi @viktorstrate , 
thanks for your reply. Yes, I am very interested in Photoview as a replacement for Google Photos that are going to start counting all images towards Google Drive quota.

**My setup:** I have a computer behind a router with port forwarding set up, that router has static IP and that computer behind it is my server (and the whole setup is pretty far away from me, physically).

**My goal:** have Photoview accessible either 
- via `https://example.org/somepath` or 
- via `https://example.org:48165` 
where example.org is my domain and that number is some random port I choose).

Thru today, I wrote here a long post explaining all the stuff I've tried to achieve either of the above (and that failed to produce a functioning setup). Then I thought, hey, stupid, what about this totally obvious setup:
- port forwarding set on the router the server is behind (set to 4242->4242, I like the number)
- the `docker-compose.yml` left at defaults except for domain, ports, and path to photo folders:
```
  photoview:
    image: viktorstrate/photoview:1
    restart: always
    ports:
      - "4242:80"
    depends_on:
      - db
...
      - PUBLIC_ENDPOINT=http://example.org:4242/
...
      - /mydrive/www/exampleorg/mobilephotos:/mobilephotos:ro

```
Then I run the `docker-compose up -d`, go to the address `http://example.org:4242`. Aaaand it works as expected! (It's awesome, as far as I can tell now :) )
So my thanks to you for telling me the setup is good which led me to trying it out on local which then led me to correct setup. 

My main question now is: would you happen to have some tutorial on how to set this up with HTTPS? Because I kinda don't feel like exposing all of my photos to my ISPs and whoever else with HTTP and I have no idea how to set SSL up with docker (I have it enforced with Apache but that doesn't apply to Docker, obviously).

My second (much less important) question is: how important is to change the MariaDB credentials in the `docker-compose.yml`? Where is it used and where are the data stored? (I didn't have to actually set up any DB myself, the app did everything on its own, which is nice, but I have no idea where is the data stored (and what data are actually stored).

Thank you very much for you time, help, and generally development of this app.

Also, I hope this "debugging" will serve someone else in the same situation.
