### DISCUSSION TITLE
Use external (installed directly on the server) MySQL server

### DISCUSSION THREAD

**Discussion by mihha** [photoview/photoview#200] [Q&A and Troubleshooting]
Hi,

I would like to use PhotoView but would like to remove MariaDB from docker-compose file because I already have MySQL server installed and optimized on the host where I would like to run PhotoView in container

Can you guys suggest the changes in docker-compose to achieve what I am looking for?

Thank you in advance!

**Comment by viktorstrate** [comment]
Hi @mihha 
You would have to use the `host` network mode, such that the photoview container shares the same network interface as the host (the server itself)

Something like this, note that I haven't tested it:

```yaml
version: "3"

services:
  photoview:
    image: viktorstrate/photoview:2
    restart: always
    network_mode: host # ADD THIS

    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=username:password@tcp(127.0.0.1)/database_name # ADD YOUR DB CREDENTIALS HERE
      - PHOTOVIEW_LISTEN_IP=127.0.0.1
      - PHOTOVIEW_LISTEN_PORT=80 # PORT PHOTOVIEW WILL BIND TO
      - PHOTOVIEW_MEDIA_CACHE=/app/cache

      # Change This: The publicly exposed url
      # For example if the server is available from the domain example.com,
      # change this value to http://example.com/
      - PHOTOVIEW_PUBLIC_ENDPOINT=http://localhost:8000/

      # Optional: To enable map related features, you need to create a mapbox token.
      # A token can be generated for free here https://account.mapbox.com/access-tokens/
      # It's a good idea to limit the scope of the token to your own domain, to prevent others from using it.
      # - MAPBOX_TOKEN=<YOUR TOKEN HERE>

    volumes:
      - api_cache:/app/cache

      # Change this to the directory where your photos are located on your server.
      # If the photos are located at `/home/user/photos`, then change this value
      # to the following: `/home/user/photos:/photos:ro`.
      # You can mount multiple paths, if your photos are spread across multiple directories.
      - ./photos_path:/photos:ro

volumes:
  api_cache:
```

**Reply by mihha** [reply]
Thank you very much for your fast reply

I will try what you suggested and will see if I can work it out

Regards,
Igor

**Reply by FuzzyMistborn** [reply]
There's no other way to do this?  Because if you set the container to host_mode then the container runs on port 80 which is already used by a lot of other things.

**Reply by viktorstrate** [reply]
@FuzzyMistborn you can change `PHOTOVIEW_LISTEN_PORT` to tell Photoview to bind to another port.

**Comment by bamnoru** [comment]
Hello,

You should use the keyword "network_mode" instead of "network" :

```
  photoview:
    image: viktorstrate/photoview:2
    restart: always
    network_mode: host

```
