### DISCUSSION TITLE
Smooth docker install but no photos is showing up in the homepage

### DISCUSSION THREAD

**Discussion by hakanu** [photoview/photoview#445] [Q&A and Troubleshooting]
Hello first time user here,

I installed with docker compose with your example yaml file, everything was fine till I log in. After login, I can not see any photos although I hit scan and scan all multiple times.

I tried to purge everything re-docker-compose-upping too. No luck.

Adding the part that I changed, LMK if this looks wrong. Feels like I messed up the photos directory setup. 

```
volumes:
      - api_cache:/app/cache

      # Change This: to the directory where your photos are located on your server.
      # If the photos are located at `/home/user/photos`, then change this value
      # to the following: `/home/user/photos:/photos:ro`.
      # You can mount multiple paths, if your photos are spread across multiple directories.
      - /home/$USER/Downloads:/photos:ro
```

```
Something went wrong
Server error: invalid root path at (userAddRootPath)

Something went wrong
Server error: user already owns a path containing this path: /app at (userAddRootPath)

Something went wrong
Server error: invalid root path at (userAddRootPath)
```

Thanks.

**Comment by viktorstrate** [comment]
Hi @hakanu welcome to :)

It sounds like you maybe didn't configure the path properly from the Settings page on the website. Would you mind sharing a screenshot of the users and their paths in your settings page?

**Comment by hakanu** [comment]
Thanks Viktor, I think i'm messing up at the docker-compose.yml part:

```
volumes:
      - api_cache:/app/cache

      # Change This: to the directory where your photos are located on your server.
      # If the photos are located at `/home/user/photos`, then change this value
      # to the following: `/home/user/photos:/photos:ro`.
      # You can mount multiple paths, if your photos are spread across multiple directories.
      - /home/$USER/Downloads:/photos/Downloads:ro
      - /home/$USER/Pictures:/photos/Pictures:ro

volumes:
  db_data:
  api_cache:
```

I couldn't find many examples around docker-compose.yml, Some links are broken in docs. I'm using this one currently: https://github.com/photoview/photoview/blob/master/docker-compose.example.yml

Do i need to set anything for volumes?
