### DISCUSSION TITLE
Can't Get Photos to Show in Web UI

### DISCUSSION THREAD

**Discussion by five2seven** [photoview/photoview#446] [Q&A and Troubleshooting]
Describe the bug
I have one folder, in Nextcloud. I can't seem to get any photos to show up in the Web UI. I've rebuilt this container dozens of times, I can see all the photos in that folder so I know the path is correct. What am I missing?
![Screenshot 2021-07-13 175302](https://user-images.githubusercontent.com/44069152/125535355-adb3a646-8a7a-4f01-beeb-7981fb79227f.png)

Your environment:

Docker
mariadb 10.5
Chrome and Firefox on Windows 10
Version 2.3.4

**My setup:**
```
version: "3"

services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=photosecret
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - db_data:/var/lib/mysql

  photoview:
    image: viktorstrate/photoview:2
    restart: always
    ports:
      - 8484:8484
    depends_on:
      - db

    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:photosecret@tcp(db)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=8484
      - PHOTOVIEW_MEDIA_CACHE=/app/cache      

    volumes:
      - api_cache:/app/cache

      # Change This: to the directory where your photos are located on your server.
      # If the photos are located at `/home/user/photos`, then change this value
      # to the following: `/home/user/photos:/photos:ro`.
      # You can mount multiple paths, if your photos are spread across multiple directories.
      - /var/www/html/nextcloud/data/user/files/Photos/:/photos:ro

volumes:
  db_data:
  api_cache:
```
