### DISCUSSION TITLE
Database refuses connections no matter what

### DISCUSSION THREAD

**Discussion by yllekz** [photoview/photoview#529] [Q&A and Troubleshooting]
**Edit: So a few days later I tried just spinning up this container once more (I had both the UI and DB containers stopped for several days), and now things just seem to be working again. I have no idea why it's working; I changed nothing. It seems to be fixed now, but it's a total mystery as to why it didn't work for so long.**

Hey folks, I'm sort of going crazy figuring out what's going on here. I recently had to rebuild my docker environment due to some unforeseen circumstances. I had my old docker-compose files so it wasn't a big deal, but photoview isn't playing nice. For some reason I continually get these errors:

```
2021/09/23 14:54:02 Connecting to MYSQL database: photoview:photoview@tcp(db:3306)/photoview?multiStatements=true&parseTime=true
2021/09/23 14:54:02 /app/database/database.go:101
[error] failed to initialize database, got error dial tcp 172.17.0.14:3306: connect: connection refused
2021/09/23 14:54:02 WARN: Could not ping database: dial tcp 172.17.0.14:3306: connect: connection refused. Will retry after 5 seconds
2021/09/23 14:54:07 Connecting to MYSQL database: photoview:photoview@tcp(db:3306)/photoview?multiStatements=true&parseTime=true
```

The IP listed there is the one docker's network assigns to it. The main container's IP is in the same network/subnet as well so that shouldn't be a problem.

I run into this problem under all of these circumstances:

- Delete/rebuild containers, same config
- Delete/rebuild containers, fresh config for db container
- Delete/rebuild containers, fresh config for photoview container
- Delete/rebuild containers, fresh config for both db + photoview container
- Delete/rebuild containers, fresh config for both db + photoview container + new database password

Is there something obvious I'm missing here? It's weird that this just worked before but now is giving me errors.

Here's my current docker-compose Stack. I'm using "photoview" as a password instead of "photosecret" due to an issue long ago and just never updated it, but that wasn't a problem before.

```
---
version: "2.1"
services:
  photoview:
    image: viktorstrate/photoview:latest
    container_name: photoview
    restart: unless-stopped
    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:photoview@tcp(db)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
      - MAPBOX_TOKEN=<my mapbox token was here>
    volumes:
      - /path/to/my/config/photoview:/app/cache
      - /path/to/my/Photos:/photos:ro
    ports:
      - 8124:80
    links:
      - db:db
  db:
    image: yobasystems/alpine-mariadb:latest
    restart: unless-stopped
    volumes:
      - /path/to/my/config/photoviewdb:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_PASSWORD=photoview
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
```
