### DISCUSSION TITLE
Docker-compose file paths

### DISCUSSION THREAD

**Discussion by Europa2010AD** [photoview/photoview#579] [Q&A and Troubleshooting] [answered]
I've got Photoview running on my NAS via docker-compose, however I'm not quite sure why my app cache and DB folders are completely empty, despite having some photos scanned already. My .yml (based on the official .yml) looks like this:
```
version: '3'
services:
  db:
    container_name: maria-db
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=photosecret
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - db_data:/share/appdata/mariadb/mysql
  photoview:
    container_name: photoview
    image: viktorstrate/photoview:2
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:photosecret@tcp(db)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/share/appdata/photoview/cache
    volumes:
      - api_cache:/share/appdata/photoview/cache
      - /share/[path_to_photo_directory]:/photos:ro
volumes:
  db_data:
  api_cache:
```
As you can see, I've configured the .yml to point to a shared volume named "appdata", and within this volume I've created both a folder for MariaDB and for Photoview. I believe there shouldn't be any problems with the file path, since I use the same path to point my Jellyfin's cache, and that cache fills up properly.

What am I doing wrong?
