### DISCUSSION TITLE
Scan doesn't scan entire photo's folder, and stops randomly.

### DISCUSSION THREAD

**Discussion by flee541** [photoview/photoview#583] [Q&A and Troubleshooting]
Hi, I am looking to replace Google photos and stumbled into Photoview. I have setup Photoview via docker (Portainer Stacks) and it seems to be working. Only thing is when I hit scan, it stops a few minutes into the scan of my mounted photos drive.

I am also seeing in the logs that the Localhost is making an unauthenticated api calls? Unsure what that means.

Below is my docker compose file (or the Portainer Stack). The volumes are volumes I created in Portainer and the photo is actually an NFS mount via portainer's volume manager.

Any help would be greatly appreciated.

```yaml
version: "2.1"

services:
  db:
    image: mariadb:latest
    restart: always
    network_mode: host
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=photosecret
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - photoview_db:/var/lib/mysql

  photoview:
    image: viktorstrate/photoview:2
    restart: always
    ports:
      - "8800:80"
    depends_on:
      - db

    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:photosecret@tcp(192.168.1.82)/photoview
      - PHOTOVIEW_LISTEN_IP=192.168.1.82
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
      
      # Optional: If you are using Samba/CIFS-Share and experience problems with "directory not found"
      # Enable the following Godebug
      # - GODEBUG=asyncpreemptoff=1
      
      
      # Optional: To enable map related features, you need to create a mapbox token.
      # A token can be generated for free here https://account.mapbox.com/access-tokens/
      # It's a good idea to limit the scope of the token to your own domain, to prevent others from using it.
      # - MAPBOX_TOKEN=<YOUR TOKEN HERE>

    volumes:
      - photoview_data:/app/cache

      # Change This: to the directory where your photos are located on your server.
      # If the photos are located at `/home/user/photos`, then change this value
      # to the following: `/home/user/photos:/photos:ro`.
      # You can mount multiple paths, if your photos are spread across multiple directories.
      - terranas-photos:/photos:ro

volumes:
  db_data:
  api_cache:
```
