### DISCUSSION TITLE
Porting Photoview from PC to Raspberry Pi 4

### DISCUSSION THREAD

**Discussion by fmnamado** [photoview/photoview#675] [Q&A and Troubleshooting]
Hello,
I am fine tuning my experience with PhotoView.
My library is very large (> 1TB), so it generates a lot of conversions and needs a lot of horse power (CPU).

My setup is this:
I have a synology NAS sharing the photo lib via SMB.
I want to run the Photoview app in my Raspberry pi 4.
It has raspberry pi OS, Open Media Vault, Docker/Portainer and Photoview runinng via Docker compose.

This is my docker compose file:

```
version: "3"

services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=photosecret
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - db_data:/var/lib/mysql

  photoview:
    image: viktorstrate/photoview:latest
    restart: always
    ports:
      - "8734:80"
    depends_on:
      - db

    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:photosecret@tcp(db)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
      - PHOTOVIEW_DISABLE_VIDEO_TRANSCODING=1
      
      # Optional: If you are using Samba/CIFS-Share and experience problems with "directory not found"
      # Enable the following Godebug
      # - GODEBUG=asyncpreemptoff=1
      
      
      # Optional: To enable map related features, you need to create a mapbox token.
      # A token can be generated for free here https://account.mapbox.com/access-tokens/
      # It's a good idea to limit the scope of the token to your own domain, to prevent others from using it.
      # - MAPBOX_TOKEN=<YOUR TOKEN HERE>

    volumes:
      #- api_cache:/app/cache
      - /portainer/Files/AppData/Config/PhotoView/api_cache:/app/cache


      # Change This: to the directory where your photos are located on your server.
      # If the photos are located at `/home/user/photos`, then change this value
      # to the following: `/home/user/photos:/photos:ro`.
      # You can mount multiple paths, if your photos are spread across multiple directories.
      - /srv/FOLDER:/photos:ro


volumes:
  db_data:
  api_cache:
```

I thought this, and I am trying this option:
Running OMV in virtual machine, dedicating it more capable hardware (my Intel CPU is faster than the rpi4).
The idea would be, in the end of the full library scan, to copy both the api_cache and other files to rpi and run it without problems.

So besides the /app/cache (/portainer/Files/AppData/Config/PhotoView/api_cache) folder, where are other relevant files?
In my attemps, i tried deleting the api_cache folder and Photoview didn't got reset. It brings me another question: what files do I need to delete to reset both Photoview, MariaDB and eventually other files?
What are the important dirs to know, copy/delete?
Is it possible to migrate from PC to rpi4 with copy and pasting some dirs, without some major pain?

Does this even makes sense?

Thank you!
