### DISCUSSION TITLE
Unable to access photoview when connecting through a Cloudflare tunnel

### DISCUSSION THREAD

**Discussion by nick-a-louse** [photoview/photoview#689] [Q&A and Troubleshooting]
I've successfully got Photoview working (it's great!) on my ubuntu server and it's accessible internally on the network.  When I try and access through a Cloudflare Argo Tunnel though, it is unauthorised.

I'm trying to figure out if the issue lies in the tunnel config or Photoview (I know it isn't a super common use-case). I'm not sure if it's possible to get any more logging out of the Photoview, but any direction would be appreciated. I'm fairly confident that the tunnel is setup correct (but happy to be wrong):

- I can access home assistant, frigate etc through the tunnel without any issues
- I get errors in the Photoview docker container (i.e. the traffic is getting through the tunnel, docker network etc)

This is the error in the Photoview docker logs (`docker-compose logs --tail 100`):

```
photoview_1  | 2022/04/25 22:33:32 Did not find auth-token cookie
photoview_1  | 2022/04/25 22:33:32 POST 200 localhost/api/graphql 424.548µs unauthenticated
```

This is the docker-compose file:

```
version: "3"

services:
  db:
    container_name: photoview_mariadb
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=photosecret
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - /opt/appdata/photoview/db_data:/var/lib/mysql
    networks:
      - photoview

  photoview:
    container_name: photoview
    image: viktorstrate/photoview:2
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - db

    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:photosecret@tcp(db)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
      - MAPBOX_TOKEN=longtokenhere


    volumes:
      - /opt/appdata/photoview/cache:/app/cache
      - /zpool/Media/Media/Pictures:/photos:ro

#volumes:
    networks:
      - cloudflared
      - photoview

networks:
  cloudflared:
    external: true
    name: cloudflared
  photoview:
    driver: bridge

```
