### DISCUSSION TITLE
Setup on Synology NAS

### DISCUSSION THREAD

**Discussion by michaelsmolka** [photoview/photoview#813] [Q&A and Troubleshooting] [answered]
Hi,
recently I found this project and it seems as it would fit my needs perfectly. So I tried to install it on my new Synology NAS.
But something went wrong and I cannot figure out what to to. Probably it's my fault.

That's what I see in the log:
`

2023-03-05T07:24:48.146693624Z | stdout | /app/server.go:45 +0x128
-- | -- | --
2023-03-05T07:24:48.146669020Z | stdout | main.main()
2023-03-05T07:24:48.146639915Z | stdout | /app/database/database.go:177 +0x66
2023-03-05T07:24:48.146609848Z | stdout | github.com/photoview/photoview/api/database.MigrateDatabase(0xe5ab29?)
2023-03-05T07:24:48.146581905Z | stdout | /go/pkg/mod/gorm.io/gorm@v1.23.7/gorm.go:395 +0x5e
2023-03-05T07:24:48.146549628Z | stdout | gorm.io/gorm.(*DB).SetupJoinTable(0x3?, {0xdb2940, 0xc000238620}, {0xe473c3, 0x6}, {0xd40d40, 0xc00020aac0})
2023-03-05T07:24:48.146514495Z | stdout | /go/pkg/mod/gorm.io/gorm@v1.23.7/gorm.go:363 +0x18
2023-03-05T07:24:48.146473704Z | stdout | gorm.io/gorm.(*DB).getInstance(0x300000002?)
2023-03-05T07:24:48.146174638Z | stdout | goroutine 1 [running]:
2023-03-05T07:24:48.146150628Z | stdout |  
2023-03-05T07:24:48.146103713Z | stdout | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7d8678]
2023-03-05T07:24:48.145652460Z | stdout | panic: runtime error: invalid memory address or nil pointer dereference
2023-03-05T07:24:43.119103586Z | stdout | 2023/03/05 07:24:43 WARN: Could not ping database: Environment variable PHOTOVIEW_MYSQL_URL missing, exiting. Will retry after 5 seconds
2023-03-05T07:24:38.114977522Z | stdout | 2023/03/05 07:24:38 WARN: Could not ping database: Environment variable PHOTOVIEW_MYSQL_URL missing, exiting. Will retry after 5 seconds
2023-03-05T07:24:33.110889659Z | stdout | 2023/03/05 07:24:33 WARN: Could not ping database: Environment variable PHOTOVIEW_MYSQL_URL missing, exiting. Will retry after 5 seconds
2023-03-05T07:24:28.110537219Z | stdout | 2023/03/05 07:24:28 WARN: Could not ping database: Environment variable PHOTOVIEW_MYSQL_URL missing, exiting. Will retry after 5 seconds
2023-03-05T07:24:23.107089059Z | stdout | 2023/03/05 07:24:23 WARN: Could not ping database: Environment variable PHOTOVIEW_MYSQL_URL missing, exiting. Will retry after 5 seconds
2023-03-05T07:24:23.107031164Z | stdout | 2023/03/05 07:24:23 No .env file found
2023-03-05T07:24:23.106055564Z | stdout | 2023/03/05 07:24:23 Starting Photoview...

<br class="Apple-interchange-newline">`

Maybe somebody already installed PhotoView on a Synology NAS and could give advice how to do it?
Thank you in advance.

**Comment by michaelsmolka** [comment]
Finally I tried to install it with Portainer. This worked so far.
Now I get error message on the inital start screen:

```
Something went wrong
Server error: internal system error at (initialSetupWizard)
```
Any idea what could cause this?

**Comment by michaelsmolka** [comment]
Tried if the solution from [#447 ](https://github.com/photoview/photoview/discussions/447#discussioncomment-1994611) helps.
But unfortunately still get this message:
<img width="515" alt="Bildschirmfoto 2023-03-05 um 14 26 16" src="https://user-images.githubusercontent.com/102899353/222963420-a87c66c3-9ff7-45fc-85c3-1db7ed90113b.png">

From the container log I see these errors:
```
2023-03-05T13:29:55.481808998Z,stdout,2023/03/05 13:29:55 [0;32;49mPOST [0;32;49m200[0m localhost/api/graphql [0;36;49m990.592µs[0m unauthenticated

2023-03-05T13:29:55.481160765Z,stderr,2023/03/05 13:29:55 Did not find auth-token cookie

2023-03-05T13:28:55.124147614Z,stdout,2023/03/05 13:28:55 [0;32;49mPOST [0;32;49m200[0m localhost/api/graphql [0;36;49m874.459µs[0m unauthenticated

2023-03-05T13:28:55.123525812Z,stderr,2023/03/05 13:28:55 Did not find auth-token cookie

2023-03-05T13:27:54.644162676Z,stdout,2023/03/05 13:27:54 [0;32;49mPOST [0;32;49m200[0m localhost/api/graphql [0;36;49m1.424277ms[0m unauthenticated

2023-03-05T13:27:54.642911401Z,stderr,2023/03/05 13:27:54 Did not find auth-token cookie

2023-03-05T13:26:54.258951327Z,stdout,2023/03/05 13:26:54 [0;32;49mPOST [0;32;49m200[0m localhost/api/graphql [0;36;49m891.104µs[0m unauthenticated

2023-03-05T13:26:54.258230059Z,stderr,2023/03/05 13:26:54 Did not find auth-token cookie

2023-03-05T13:25:53.785277416Z,stdout,2023/03/05 13:25:53 [0;32;49mPOST [0;32;49m200[0m localhost/api/graphql [0;36;49m729.449µs[0m unauthenticated

2023-03-05T13:25:53.784504149Z,stderr,2023/03/05 13:25:53 Did not find auth-token cookie

```

**Comment by michaelsmolka** [comment, marked as answer]
Finally I got it working!

My main mistake was to insert the absolute path in the setup screen. After changing this to the default /photos (path inside the container) it worked.
Additionally I figured out, that there are some additional or variant entries necessary in the compose file. (The corresponding folders on the host system I had to create manually)

For me the easiest way was to set it up using a portainer stack.

Here is my compose file. Maybe it can help others who want so run PhotoView on a Synology Diskstation:
```
version: "3"

services:
  db:
    container_name: photoview_mariadb
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=photosecret
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
     # - db_data:/var/lib/mysql
      - /volume1/docker/photoviewdb:/var/lib/mysql

  photoview:
    image: viktorstrate/photoview
    restart: always
    ports:
      - "4711:80"
    depends_on:
      - db

    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:photosecret@tcp(photoview_mariadb)/photoview
      - PHOTOVIEW_LISTEN_IP=192.168.188.174
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
      - PHOTOVIEW_API_ENDPOINT=https://<insertyourdomainname>/api/
      
      # Optional: If you are using Samba/CIFS-Share and experience problems with "directory not found"
      # Enable the following Godebug
      # - GODEBUG=asyncpreemptoff=1
      
      
      # Optional: To enable map related features, you need to create a mapbox token.
      # A token can be generated for free here https://account.mapbox.com/access-tokens/
      # It's a good idea to limit the scope of the token to your own domain, to prevent others from using it.
      # - MAPBOX_TOKEN=<YOUR TOKEN HERE>

    volumes:
      - /volume1/docker/photoview/api_cache:/app/cache

      # Change This: to the directory where your photos are located on your server.
      # If the photos are located at `/home/user/photos`, then change this value
      # to the following: `/home/user/photos:/photos:ro`.
      # You can mount multiple paths, if your photos are spread across multiple directories.
      - /volume1/homes/michael/Photos/:/photos:ro

volumes:
  db_data:
  api_cache:
```
