### ISSUE TITLE
can't start the docker

### ISSUE THREAD

**Issue by jbrodriguez** [photoview/photoview#1006]
i can't get the docker running

i already have a docker-compose, so i'm including the service definition there

```
...
  photoview:
    image: viktorstrate/photoview:master
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    hostname: photoview
    container_name: photoview
    stop_grace_period: 10s
    ports:
      - "8000:80" ## HTTP port (host:container)
    ## Security options for some restricted systems
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      PGID: 1000
      PUID: 1000
      PHOTOVIEW_DATABASE_DRIVER: sqlite
      PHOTOVIEW_SQLITE_PATH: /home/photoview/database/photoview.db
      PHOTOVIEW_LISTEN_IP: 0.0.0.0
      # PHOTOVIEW_LISTEN_PORT: 80
    devices:
      - "/dev/nvidia0:/dev/nvidia0"
      - "/dev/nvidiactl:/dev/nvidiactl"
      - "/dev/nvidia-uvm:/dev/nvidia-uvm"
      - "/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools"
    volumes:
      - "/etc/localtime:/etc/localtime:ro" ## use local time from host
      - "/etc/timezone:/etc/timezone:ro"   ## use timezone from host
      - /<path>/photoview/database:/home/photoview/database
      - /<path>/photoview/storage:/home/photoview/media-cache
      - /<path>/media:/photos:ro"
...
```
however, when running the service, i get

```bash
╰─❯ docker compose -f ~/.config/docker-compose.yaml up photoview
[+] Running 1/0
 ✔ Container photoview  Created                                                                                                                                                                                                                                         0.0s
Attaching to photoview
photoview  | 2024/08/01 16:43:37 Starting Photoview...
photoview  | 2024/08/01 16:43:37 No .env file found
photoview  | 2024/08/01 16:43:37 Utilizing sqlite database driver based on environment variables
photoview  | 2024/08/01 16:43:37 WARN: Could not ping database: unable to open database file: no such file or directory. Will retry after 5 seconds
photoview  |
photoview  | 2024/08/01 16:43:37 /app/api/database/database.go:103
photoview  | [error] failed to initialize database, got error unable to open database file: no such file or directory
^CGracefully stopping... (press Ctrl+C again to force)
[+] Stopping 1/1
 ✔ Container photoview  Stopped                                                                                                                                                                                                                                         0.2s
canceled
```

entering the container gives me this
```bash
╰─❯ docker exec -it photoview sh
$ ls -al
total 41
drwxr-xr-x 1 photoview photoview 4096 Aug  1 16:42 .
drwxr-xr-x 1 root      root      4096 Jul 23 14:57 ..
-rw-r--r-- 1 photoview photoview  220 Mar 29 14:40 .bash_logout
-rw-r--r-- 1 photoview photoview 3526 Mar 29 14:40 .bashrc
-rw-r--r-- 1 photoview photoview  807 Mar 29 14:40 .profile
drwxr-xr-x 2      1000      1000    2 Aug  1 16:23 database
drwxr-xr-x 2      1000      1000    2 Aug  1 16:24 media-cache
$ ls -al database
total 13
drwxr-xr-x 2      1000      1000    2 Aug  1 16:23 .
drwxr-xr-x 1 photoview photoview 4096 Aug  1 16:42 ..
```

any clues/suggestions ?
