### ISSUE TITLE
PHOTOVIEW_LISTEN_IP ignored.

### ISSUE THREAD

**Issue by Cadynum** [photoview/photoview#1010]
**Describe the bug**
Photoview listens to 0.0.0.0 when it's supposed to only listen to localhost. It incorrectly claims that it's listening to 127.0.0.1 in the logs.

Tested with PHOTOVIEW_LISTEN_IP set to 127.0.0.1 and unset.  Same result.

```
$ docker compose logs
photoview  | 2024/08/06 23:40:46 Photoview API endpoint listening at http://127.0.0.1:3441/api

```

```
# ss -lpnt
State  Recv-Q Send-Q Local Address:Port Peer Address:PortProcess                         
LISTEN 0      4096               *:3441            *:*    users:(("photoview",pid=10503,fd=11))
```

**To Reproduce**
`$ docker compose up --build`

compose.yaml:
```
services:
  photoview:
    image: viktorstrate/photoview:latest
    container_name: photoview
    network_mode: host
    read_only: true
    hostname: photoview
    restart: unless-stopped
    stop_grace_period: 10s

    healthcheck:
      disable: true

    user: 1111:1111

    ## Security options for some restricted systems
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    environment:
      PHOTOVIEW_DATABASE_DRIVER: "sqlite"
      PHOTOVIEW_SQLITE_PATH: "/db/db.sqlite"
      PHOTOVIEW_LISTEN_PORT: 3441
      PHOTOVIEW_SERVE_UI: 1
      PHOTOVIEW_MEDIA_CACHE: "/cache"
      PHOTOVIEW_DISABLE_FACE_RECOGNITION: 1

    volumes:
      - cache:/cache
      - db:/db
      - "/etc/localtime:/etc/localtime:ro"

volumes:
  cache:
  db:
```

**Your environment:**
* Latest docker arm64 as of 2024-08-06
* Running on Raspberry Pi OS for Raspberry Pi 5
* Docker network mode is set to host.
