### ISSUE TITLE
Support `imagemagick` and `ffmpeg-jellyfin` tools to convert photos and videos.

### ISSUE THREAD

**Issue by googollee** [photoview/photoview#1011]
Conclusion:

- [x] Build `imagemagick`/`libraw`/`libheif` under `debian:bookworm`
- [x] Install `imagemagick` instead of `darktable`
  - Update the worker commands.
- [x] Install `ffmpeg-jellyfin` instead of `ffmpeg` from Debian.
  - Provide `PHOTOVIEW_VIDEO_CODEC` for the conversion codec

**Is your feature request related to a problem? Please describe.**
There are a group of requirement to support other tools than `darktable` or normal `ffmpeg` to convert photos and videos, like https://github.com/photoview/photoview/issues/928 and https://github.com/photoview/photoview/issues/652. We should provide a solution to let user custom tools they want to use.

**Describe the solution you'd like**
Add environments to define scripts to call when converting photos and videos.

```sh
PHOTOVIEW_SCRIPT_BIN=/bin/sh
PHOTOVIEW_SCRIPT_CONVERT_PHOTO=/app/scripts/worker/darktable.sh
PHOTOVIEW_SCRIPT_CONVERT_VIDEO=/app/scripts/worker/ffmpeg.sh
PHOTOVIEW_SCRIPT_CONVERT_VIDEO_CODEC=h264
```

- `PHOTOVIEW_SCRIPT_BIN` defines the command to run scripts.
  - The environment should provide the command in the environment.
  - It's `/bin/sh` by default. It's common in most of Linux environment.
- `PHOTOVIEW_SCRIPT_CONVERT_PHOTO` should be called like: `<script> <input file> <output file> <jpg quality, 0-100>`.
  - It's `/app/scripts/worker/darktable.sh` by default. The content is the same as current command with `darktable`.
- `PHOTOVIEW_SCRIPT_CONVERT_VIDEO` should be called like: `<script> <input file> <output file> <value of PHOTOVIEW_SCRIPT_CONVERT_VIDEO_CODEC>`.
  - It's `/app/scripts/worker/ffmpeg.sh` by default. The content is the same as current command with `ffmpeg`.
- `PHOTOVIEW_SCRIPT_CONVERT_VIDEO_CODEC` defines the codec when converting videos. The value depends on the tool specified by `PHOTOVIEW_VIDEO_CONVERT_SCRIPT`. 
  - It's `h264` by default, the same as current codec.
  - If `PHOTOVIEW_SCRIPT_CONVERT_VIDEO` supports codec with the hardware acceleration like `h264_qsv`, `PHOTOVIEW_SCRIPT_CONVERT_VIDEO_CODEC` could use it with the proper hardware.

**Describe alternatives you've considered**
We could use environment to define the command directly, like below:

```sh
PHOTOVIEW_CONVERT_PHOTO="darktable ${ .INPUT } ${ .OUTPUT } --core --conf plugins/imageio/format/jpeg/quality=${ .JPEGQuality } --configdir /tmp"
```

It's hard to write multiple-line commands, like creating a tmp dir first and deleting it at the end. Also it's easy to forget quote parameters in the command, especially for input and output. If a file path contains an space, the command will fail.

**Comment by kkovaletp** [comment]
@googollee, thanks for this idea. I think that this is 1 of the most wanted architectural changes in the product, which might cover and solve many open issues in the project. I definitely would like to have this feature implemented)

But let me please provide some concerns and questions about the proposed implementation:
- I see a huge security issue in the fact of running user-written scripts. This implementation could be easily exploited in malicious ways. Instead, I'd propose to define a config file structure, where a user can describe all the needed params for an executable from the list of preinstalled tools in the image (or installed on the host with the Photoview server manually by a user) 
- As this is a change in the core product functionality and architecture, we need to carefully think about different possible use cases, design the solution, implement, and test it. This will take some time, but these efforts are crucial to not miss something important and not introduce some critical bugs.
- Do we want to provide the possibility to run a tool remotely on a different host or just outside of the main image? If yes, I think that the best way would be to implement an HTTP server (similar to my PoC in the https://github.com/kkovaletp/photoview/blob/hw-gpu-support/ffmpeg-image/server.py) - this is pretty secure and easily manageable communication way, while still not so expensive from system resources usage perspective and fast. In this case, our config should support such use cases and we need to provide an example of such web-server configs for all currently supported tools.
- As this config would be a user-editable and pretty-complex configuration interface, we need to invest additional efforts into making it as more intuitive and self-descriptive, as possible. Also, we'd probably need to provide a detailed guide for the configuration of the product for the major supported setups: I predict a lot of requests for support and issue reports because of user misunderstanding and misconfiguration.
- Also, we'd need to implement the detailed logging of the config parsing process, including all possible edge cases and incorrect values: there must be no logical execution branches with no user-understandable logging.
- We need to limit the list of output formats and codecs based on the list of supported and expected by Photoview ones to be loaded from the media-cache sub-folders.
- As you mentioned in the issue, we need to predict possible edge cases of the params' values (paths with spaces, relative links, network paths, etc.). I don't say that we need to implement support for all possible values, but we need to predict and reject unsupported ones with meaningful justifications.

**Comment by googollee** [comment]
> I see a huge security issue in the fact of running user-written scripts. ... I'd propose to define a config file structure, ... from the list of preinstalled tools in the image ... (or installed on the host ... by a user)

Could you provide an example of this structure? It limits the support of a list of tools, and users can't install arbitrary tools themselves. The latter is the requirement of https://github.com/photoview/photoview/issues/928.

> Do we want to provide the possibility to run a tool remotely on a different host or just outside of the main image?

As we have discussed, I don't want to go that way. An external service requires the sharing of files between hosts, even if they run on the same host. I'll say it's another big feature and I hope to discuss it separately.

**Comment by kkovaletp** [comment]
> It limits the support of a list of tools, and users can't install arbitrary tools themselves

Yes, that is the idea: we cannot let a user integrate any 3rd-party executable as a worker because it could be malicious software or perform some destructive operations. As we're in charge of the final result of the Photoview usage, we have to limit the list of integrations to the amount of tools we tested. This is because we provide not a library, service worker, or operating system (where there are user expectations to be open for any input matching to the defined interface), but an end-user product, fully responsible for processing a user's input data and providing output results.

> Could you provide an example of this structure?

Well, the technical implementation depends on Go's and our framework's ability to process different config formats (or at least how easy is it to add and integrate a needed library), but I'd prefer the YAML format, as it is powerful enough, while visually clear and understandable. Also, we already provide YAML-based config to users (Docker Compose), so by adding additional config in this format we won't increment the list of to-be-known technologies for most of our users.
The final config structure has to be iteratively aligned to the list of final requirements and implementation limitations, which are not defined yet, but here is a logical preview of such a config:
```yaml
workers:
  media-format-detectors:
    # tool can be 1 of: 'ffprobe', 'imagemagick', 'darktable', 'exiftool'
    # you can chain tools to be run for the same file in the order, they are defined here
    - tool: imagemagick
      # params should be ordered in the same way, the tool's executable expects them in the shell invocation string
      params:
        - "{{input-file-path}}"
    - tool: ffprobe
      # params should be ordered in the same way, the tool's executable expects them in the shell invocation string
      params:
        - "{{input-file-path}}"

  exif:
    # tool can be 1 of: 'exiftool', '?? any other tool ??'
    tool: exiftool
    # params should be ordered in the same way, the tool's executable expects them in the shell invocation string
    params:
      - "{{input-file-path}}"

  images:
    # tool can be 1 of: 'darktable', 'imagemagick'
    tool: darktable
    # params should be ordered in the same way, the tool's executable expects them in the shell invocation string
    params:
      - "{{input-file-path}}"
      - "{{output-file-path}}"
      - "--core"
      - "--conf"
      - "plugins/imageio/format/jpeg/quality=90"
      - "--configdir "

  videos:
    thumbnails:
      # tool can be 1 of: 'ffmpeg', '?? any other tool ??'
      tool: ffmpeg
      # params should be ordered in the same way, the tool's executable expects them in the shell invocation string
      params:
        - "-ss {{thumbnail-offset-seconds}}"
        - "-i, {{input-file-path}}"
        - "-vframes 1"
        - "-an"
        - "-vf scale='min(1024,iw)':'min(1024,ih)':force_original_aspect_ratio=decrease:force_divisible_by=2"
        - "{{output-file-path}}"
    videos:
      # tool can be 1 of: 'ffmpeg', '?? any other tool ??'
      tool: ffmpeg
      # params should be ordered in the same way, the tool's executable expects them in the shell invocation string
      params:
        - "-i, {{input-file-path}}"
        - "-vcodec h264"
        - "-acodec aac"
        - "-vf scale='min(1080,iw)':'min(1080,ih)':force_original_aspect_ratio=decrease:force_divisible_by=2"
        - "-movflags +faststart+use_metadata_tags"
        - "{{output-file-path}}"
```
