### ISSUE TITLE
Can't Connect to MariaDB Database

### ISSUE THREAD

**Issue by royaltongue** [photoview/photoview#369]
My `docker-compose.yml`:
```
version: "3"

services:
  photoviewdb:
    container_name: photoviewdb
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=[redacted]
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - /mnt/storage/DockerContainerStorage/photoview/db:/var/lib/mysql
    networks:
      - caddy_net

  photoview:
    container_name: photoview
    image: viktorstrate/photoview:2
    restart: always
    ports:
      - "8088:80"
    depends_on:
      - photoviewdb

    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:[redacted]@tcp(photoviewdb)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
      
      # Optional: If you are using Samba/CIFS-Share and experience problems with "directory not found"
      # Enable the following Godebug
      # - GODEBUG=asyncpreemptoff=1
      
      
      # Optional: To enable map related features, you need to create a mapbox token.
      # A token can be generated for free here https://account.mapbox.com/access-tokens/
      # It's a good idea to limit the scope of the token to your own domain, to prevent others from using it.
      # - MAPBOX_TOKEN=<YOUR TOKEN HERE>

    volumes:
      - /mnt/storage/DockerContainerStorage/photoview/cache:/app/cache

      # Change This: to the directory where your photos are located on your server.
      # If the photos are located at `/home/user/photos`, then change this value
      # to the following: `/home/user/photos:/photos:ro`.
      # You can mount multiple paths, if your photos are spread across multiple directories.
      - /mnt/storage/photos/googlephotos05092021:/photos/googlephotos05092021:ro
    networks:
      - caddy_net


networks:
  caddy_net:
    external: true
```

And the error I'm receiving:
```
2021/05/12 14:18:54 Connecting to MYSQL database: photoview:[redacted]@tcp(photoviewdb:3306)/photoview?multiStatements=true&parseTime=true
2021/05/12 14:18:54 WARN: Could not ping database: Error 1045: Access denied for user 'photoview'@'192.168.48.39' (using password: YES). Will retry after 5 seconds
2021/05/12 14:18:54 /app/database/database.go:101
[error] failed to initialize database, got error Error 1045: Access denied for user 'photoview'@'192.168.48.39' (using password: YES)
```

I feel like I messed something up in the MYSQL URL, but I'm not sure what. Advice?

EDIT: Also, my password does not contain a hyphen, as described in a similar issue about this problem
