### ISSUE TITLE
Failed to begin database transaction: failed to process photo: no such file or directory

### ISSUE THREAD

**Issue by XanderStrike** [photoview/photoview#391]
**Describe the bug**
When scanning my library, I receive errors for many photos, and those photos never appear in my library.

**To Reproduce**
1. Launch the app with a directory of problematic photos
    * Seems to be any Canon RAW (CR2) files taken with my 40D or 7D
2. Scan all users
4. Observe the following in logs and in error alerts:

```
photoview_1  | 2021/06/05 18:17:24 ERROR: Failed to begin database transaction: failed to process photo 
(/photos/2012-11-30/IMG_0100.CR2): open /app/cache/676/59286/highres_IMG_0100_CR2_y7Kg4DnG.jpg:
no such file or directory
photoview_1  | 2021/06/05 18:17:24 ERROR: Failed to begin database transaction: failed to process photo 
(/photos/2012-11-30/IMG_0101.CR2): open /app/cache/676/59287/highres_IMG_0101_CR2_HFT3OFa6.jpg: 
no such file or directory
photoview_1  | 2021/06/05 18:17:25 ERROR: Failed to begin database transaction: failed to process photo 
(/photos/2012-11-30/IMG_0102.CR2): open /app/cache/676/59288/highres_IMG_0102_CR2_pjTFPUK2.jpg:
no such file or directory
```

**Expected behavior**
I expect all CR2 files to be processed successfully

OR

I expect descriptive errors that explain why these images can't be processed (and ideally, how to repair them)

**Screenshots**
![image](https://user-images.githubusercontent.com/1565303/120902029-e46c6a80-c5f2-11eb-91ed-5ac3f0b55c0e.png)

**Your environment:**
Feel free to remove and add what you think might be useful.

 - Are you using Docker?  [Yes]
 - Database [mariadb 10.5]
 - Version [latest as of this morning]

**Additional context**

<details>
  <summary>docker-compose.yaml</summary>

```
services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=photosecret
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - /home/xander/configs/photoview/db:/var/lib/mysql

  photoview:
    image: viktorstrate/photoview:2
    restart: always
    ports:
      - "8888:80"
    depends_on:
      - db

    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:photosecret@tcp(db)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache

      # Optional: If you are using Samba/CIFS-Share and experience problems with "directory not found"
      # Enable the following Godebug
      # - GODEBUG=asyncpreemptoff=1


      # Optional: To enable map related features, you need to create a mapbox token.
      # A token can be generated for free here https://account.mapbox.com/access-tokens/
      # It's a good idea to limit the scope of the token to your own domain, to prevent others from using it.
      - MAPBOX_TOKEN=<redacted, but supplied>

    volumes:
      - /home/xander/configs/photoview/cache:/app/cache

      # Change This: to the directory where your photos are located on your server.
      # If the photos are located at `/home/user/photos`, then change this value
      # to the following: `/home/user/photos:/photos:ro`.
      # You can mount multiple paths, if your photos are spread across multiple directories.
      - /mnt/tank/photos:/photos:ro
```
</details>

A sample of pictures causing the problem: [ProblematicPictures.zip](https://github.com/photoview/photoview/files/6603034/ProblematicPictures.zip). If you are (rightfully) squeemish about opening a zip file from a stranger I'm happy to put these in google drive or similar, just let me know.
