### ISSUE TITLE
Docker - no way of setting up PUID/PGUID of the user which runs photoview

### ISSUE THREAD

**Issue by Dinth** [photoview/photoview#612]
**Is your feature request related to a problem? Please describe.**
Photoview docker always runs photoview service as user root (?). Its not possible to set up PUID and PGID manually. Because of that it's not possible to use NFS volumes for photo storage. 

**Describe the solution you'd like**
PUID and PGID environment variables for docker.

**Describe alternatives you've considered**
There's no alternative i can see - my photos are stored on a hardware solution which only allows NFS access for user PUID=1007 and PGID=100. 

**Additional context**

**Comment by viktorstrate** [comment]
Does it work if you add a `user` attribute to the service in the docker compose file?

```diff
  photoview:
    image: viktorstrate/photoview:2
+   user: "${UID}:${GID}"
    restart: always
```

I am not sure if there should be a reason to support custom environment variables like `PHOTOVIEW_UID` and `PHOTOVIEW_GID`, if someone has good arguments for that, I'd like to hear them.

I may be a good idea to change the default user to something other than root if that is the default?
I don't know the convensions for this though.

**Comment by Dinth** [comment]
Thanks for your reply Viktorstrate. I will try your solution with user: attribute, hopefully thats gonna work. In the meantime, im definetely not a power user when it comes to docker, just an ordinary home user with no more than 50 containers, but until now i thought that PUID and PGID attributes are standard on any containers accessing data volumes.

**Comment by LeeThompson** [comment]
Linuxserver.io does this all the time, might be able to look at how they do it and borrow it for Photoview.

**Comment by catchdave** [comment]
This is my dockerfile I have used to run photoview as non-root. Note: the healthcheck is hard-coded to port 80 which will not bind in a non-root container, so it has to be modified in the compose yaml.

```
version: "3.4"

services:
  db:
    user: $UID:$GID
    image: mariadb:10.5
    container_name: photoview-mysql-1
    restart: always
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=${dbPass}
      - MYSQL_RANDOM_ROOT_PASSWORD=${rootPass}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/passwd:/etc/passwd:ro
      - /path/to/docker/storage/photoview:/var/lib/mysql

  photoview:
    user: $UID:$GID
    container_name: photoview-1
    image: viktorstrate/photoview:2
    restart: always
    ports:
      - "8008:8080"
    depends_on:
      - db
    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:${dbPass}@tcp(db)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=8080
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
      - MAPBOX_TOKEN=<redacted>
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/passwd:/etc/passwd:ro
      - /path/to/docker/storage/photoview/api_cache:/app/cache
      - /path/to/photo/storage/photos:/photos:ro
    healthcheck:
      test: >
        curl --fail http://localhost:8080/api/graphql -X POST -H 'Content-Type: application/json' --data-raw '{"operationName":"CheckInitialSetup","variables":{},"query":"query CheckInitialSetup { siteInfo { initialSetup }}"}'
      interval: 60s
      timeout: 10s
```
