### ISSUE TITLE
Photos importing but not displaying, download results in an empty file

### ISSUE THREAD

**Issue by jsaltzman** [photoview/photoview#708]
Photos are importing, and I can see metadata. But in the browser they do not display. When I download a photo to test, it is an empty file. I am running a docker container on unraid.

**Comment by mj-crawl** [comment]
I had the same issue with a mariadb-container version 10.1. 

Try using mariadb:10.5 as described in the [docker-compose.example.yml](https://github.com/photoview/photoview/blob/master/docker-compose.example.yml)

**Comment by TheKeyLimePie** [comment]
I'm having the same issue with images not being processed properly (using docker-compose together with mariadb:10.5 as mentioned above). When scanning for new files, they do get imported and are shown as white empty cards on the webpage. Unfortunately, they don't seem to get transferred to the processing queue. I've wiped my Photoview instance a couple of times now, re-imported everything and it always stops processing images at the same point in my photo chronicle. My album holds more than 5k images and after about 3.5k files it does not continue processing.
With a smaller album (almost 300 files) everything works out just fine...

**Comment by kkovaletp** [comment]
Issue is fixed by #892. Closing as completed.

**Comment by Darkatek7** [comment]
> Issue is fixed by #892. Closing as completed.

No i still have this issue:

This is my docker-compose
```
version: "3"
services:
  #db:
  #  image: mariadb:10.5
  #  restart: always
  #  environment:
  #    - MYSQL_DATABASE=photoview
  #    - MYSQL_USER=photoview
  #    - MYSQL_PASSWORD=photosecret
  #    - MYSQL_RANDOM_ROOT_PASSWORD=1
  #    - TZ=Europe/Vienna
  #  volumes:
  #    - db_data:/var/lib/mysql
  photoview:
    image: viktorstrate/photoview:2
    restart: always
    ports:
      - 3015:80
    #depends_on:
    #  - db
    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
      - TZ=Europe/Vienna
      - PHOTOVIEW_DATABASE_DRIVER=sqlite
      - PHOTOVIEW_SQLITE_PATH=/app/database/photoview.db
      # Optional: If you are using Samba/CIFS-Share and experience problems with "directory not found"
      # Enable the following Godebug
      # - GODEBUG=asyncpreemptoff=1


      # Optional: To enable map related features, you need to create a mapbox token.
      # A token can be generated for free here https://account.mapbox.com/access-tokens/
      # It's a good idea to limit the scope of the token to your own domain, to prevent others from using it.
      # - MAPBOX_TOKEN=<YOUR TOKEN HERE>

    volumes:
      - api_cache:/app/cache
      - /media/mount/View/Upload:/photos:ro
      - /home/myuser/photoview/database:/app/database
volumes:
  db_data: null
  api_cache: null
networks: {}
```
