### ISSUE TITLE
Server error: internal system error at (initialSetupWizard)

### ISSUE THREAD

**Issue by Smiggel** [photoview/photoview#755]
**Describe the bug**
Added stack (below) and visited the page. I tried to complete the setup. Set the username and password. As filepath I set /photos.

Changing the path to something else not used in the stack works. But when I try to update the path in the settings, I can not set it to /photos either.

**To Reproduce**
1. User stack below to setup docker with own variables.
2. Go to the interface
3. Fill username and password
4. Set path to /photos

**Expected behavior**
After submitting, I expected the setup to complete.

**Screenshots**
<img width="950" alt="Schermafbeelding 2022-10-10 om 10 19 55" src="https://user-images.githubusercontent.com/1825953/194824497-b49af202-86df-4f2d-aeff-f782ea907be1.png">

**Your environment:**
Raspberry PI 4 + OpenMediaVault + Docker

 - Are you using Docker? [yes]
 - Database [mariadb 10.x]
 - Browser [Firefox 105.0.2]
 
**Additional context**
```
version: "3"

services:
  photoview:
    image: viktorstrate/photoview:2
    restart: always
    ports:
      - "5000:80"
    environment:
      - PUID=1000
      - PGID=1000
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:photoview@tcp(192.168.1.94:3306)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80

      # Change This: to the directory where your photos are located on your server.
      # If the photos are located at `/home/user/photos`, then change this value
      # to the following: `/home/user/photos:/photos:ro`.
      # You can mount multiple paths, if your photos are spread across multiple directories.
      - /srv/dev-disk-by-uuid-6da15416-013d-4e63-930e-2bd24701f958/Pictures:/photos:ro
```
