### ISSUE TITLE
Photoview doesn't generate/show thumbnils

### ISSUE THREAD

**Issue by ituri** [photoview/photoview#757]
Using the latest docker-compose file, I set up photoview on my local server. The photos are on a different drive which is mounted via NFS. Also the media cache is supposed to be on the different drive too. It is also mounted via NFS. Here's my `docker-compose.yml`:

```
version: "3"

services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=photosecret
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - db_data:/var/lib/mysql

  photoview:
    image: viktorstrate/photoview:2
    restart: always
    ports:
      - "8202:80"
    depends_on:
      - db

    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:photosecret@tcp(db)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/mnt/docker/photoview

      # Optional: If you are using Samba/CIFS-Share and experience problems with "directory not found"
      # Enable the following Godebug
      - GODEBUG=asyncpreemptoff=1


      # Optional: To enable map related features, you need to create a mapbox token.
      # A token can be generated for free here https://account.mapbox.com/access-tokens/
      # It's a good idea to limit the scope of the token to your own domain, to prevent others from using it.
      - MAPBOX_TOKEN=secret

    volumes:
      - api_cache:/app/cache

      # Change This: to the directory where your photos are located on your server.
      # If the photos are located at `/home/user/photos`, then change this value
      # to the following: `/home/user/photos:/photos:ro`.
      # You can mount multiple paths, if your photos are spread across multiple directories.
      - /mnt/photo:/photos:ro

volumes:
  db_data:
  api_cache:
```

Here is a screenshot of photoview after it was supposed to have generated the thumbnails:
![Screenshot 2022-10-11 at 14 13 33](https://user-images.githubusercontent.com/871297/195086657-6e7cb6d6-c8fe-48af-9ae8-79e85ac4dd2c.png)
The log is full of messages like this:
```
2022/10/11 12:12:39 Queue waiting for lock
2022/10/11 12:12:39 Queue running: in_progress: 2, max_tasks: 3, queue_len: 10
2022/10/11 12:12:39 Queue starting job
2022/10/11 12:12:39 Queue waiting
2022/10/11 12:12:39 Starting job
2022/10/11 12:12:39 Job finished
```

When I enter the docker container, I can also succesfully write to the media cache directory so I don't suppose it's a permission issue. Any ideas on what to do here?
