### ISSUE TITLE
During scan, all albums are 'server forbiden'. If I stop scan, I can't start again. 

### ISSUE THREAD

**Issue by Luis-Lourenco** [photoview/photoview#783]
**Describe the bug**
During the scan, all albums are 'forbidden by server'

I'm installing a new fresh docker with PV and MariaDB on my albums, about 415k photos and movies mov and mp4, on 6k directories, each directory are album/ sub1 album/ sub 2album.
also to check filename I use detox from apt to clean filenames before run Scan. 

**To Reproduce**
Fresh install and finish the setup. 

you can see the albums list on a black square (scan don't start yet)
start scan
all albums disappear and someones gets black, but you get error forbid by server. 
also on TimeLine addd pictures are forbidden or with broken symbol. 

if reboot container of stop and start,
after this I'm unable to scan again, I click the Scan button, but nothings happened. 

**Expected behavior**
During scan, album forbidden and TimeLine photos are broken. 

**Screenshots**

<img width="1347" alt="Screenshot 2022-12-11 at 17 09 06" src="https://user-images.githubusercontent.com/29854768/206918122-02742658-4fc3-4df6-8462-792c6628c073.png">

<img width="1113" alt="Screenshot 2022-12-11 at 17 09 24" src="https://user-images.githubusercontent.com/29854768/206918130-f90e14b5-9cbd-4ff7-825d-552c341118d0.png">

**Your environment:**
 - Are you using Docker? yes on OMV 6 over a Debian 11
 - mariadb 10.5 docker
 - Chrome snd safari on MacOS
 - Version [e.g. 2.0.0]

Photoview Version
Release Version
2.3.13 ([446ef9a4](https://github.com/photoview/photoview/commit/446ef9a46485bd18bb1c6890d485344786a4e90c))
Build date
2022-07-26T18:26:27Z

Docker compose file
```
version: "3"

services:
  db:
    image: mariadb:10-focal
    restart: always
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=phot
      - MYSQL_PASSWORD=photosecret
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - dir4:/var/lib/mysql

  photoview:
    image: viktorstrate/photoview:2
    restart: always
    ports:
      - "8022:80"
    depends_on:
      - db
#    devices:
#      - /dev/dri/card0:/dev/dri/card0
#      - /dev/dri/renderD128:/dev/dri/renderD128
      
    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=phot:photosecret@tcp(db)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
      - PHOTOVIEW_DISABLE_FACE_RECOGNITION=1
      - PHOTOVIEW_DISABLE_RAW_PROCESSING=1
      - PHOTOVIEW_DISABLE_VIDEO_ENCODING=1
      
      # Optional: If you are using Samba/CIFS-Share and experience problems with "directory not found"
      # Enable the following Godebug
      # - GODEBUG=asyncpreemptoff=1
      
    volumes:
      - /srv/dev-disk-by-uuid-460d2866-9d8d-41a7-8c4b-0b994c54a4ec/sh1/cache:/app/cache

      # Change This: to the directory where your photos are located on your server.
      # If the photos are located at `/home/user/photos`, then change this value
      # to the following: `/home/user/photos:/photos:ro`.
      # You can mount multiple paths, if your photos are spread across multiple directories.
      - /srv/dev-disk-by-uuid-460d2866-9d8d-41a7-8c4b-0b994c54a4ec/sh1:/photos:ro
      - /srv/dev-disk-by-uuid-973d3bbc-3e29-4dd1-91cf-a793c5e5cb36/sh2:/photos2:ro
      
  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    ports:
      - 8085:8080
    volumes:
      - /dir0/:/data/sh1
      - /dir1:/data/sh2

    environment:
      - FB_BASEURL=/filebrowser
    restart: always
```

Thank you
