### ISSUE TITLE
server photoview setup issue

### ISSUE THREAD

**Issue by swenthrax** [photoview/photoview#784]
**Describe the bug**
I cannot setup my Photoview server because, as soon as I set my username-password and photos path, this error appears: 
(Server error: internal system error at (initialSetupWizard)

I use this compose file: 

```
version: "3"

services:
  db:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=photosecret
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - db_data:/var/lib/mysql

  photoview:
    image: viktorstrate/photoview:2
    restart: unless-stopped
    ports:
      - "XXXX:XXXX"
    depends_on:
      - db

    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:photosecret@tcp(192.168.XXX.XXX:XXXX)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
      # - GODEBUG=asyncpreemptoff=1
      - MAPBOX_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

    volumes:
      - api_cache:/app/cache
      - /srv/dev-disk-by-uuid-e48c23c1-eva6-48bf-0012-11m5444f8582/Media/Photos:/photos:ro

volumes:
  db_data:
  api_cache:
```

**Your environment:**
 - Are you using Docker? [yes]
 - Database [e.g. mariadb 10.5]
 - Browser [chrome]
 - Version [e.g. 108.0]
