### ISSUE TITLE
Scanner random return Exif ErrBufferTooSmall

### ISSUE THREAD

**Issue by zionio** [photoview/photoview#852]
**Describe the bug**
Scanning new albums returns no error, but randomly missing `exif_id` generation inside database.

It's a very strange behavior because sometimes the scan populates the `exif_id` correctly while repeating the process does not.

**To Reproduce**
1. Start container with `docker-compose up -d`
2. Complete setup, configure `Photo path` and start `scan`
3. Verify missing exif with `select exif_id,path from media where exif_id is null;`
4. `docker-compose down`
5. purge db
6. purge cache
7. GOTO 1 and repeat

**Expected behavior**
Would expect that with each scan the data will always be correct, or at least the same as the previous scan.

**Your environment:**

 - Are you using Docker?  **yes**
 - Database: **PostgreSQL 13.11 EL7 x86_64**
 - Browser: **Chrome 114.0.5735.106**
 - Version: **2.3.13 (446ef9a4)**

**Additional context**

My `docker-compose.yml`

```
version: "3"

services:
  photoview:
    container_name: photoview
    image: viktorstrate/photoview:2
    restart: unless-stopped
    ports:
      - "8082:80"

    environment:
      PHOTOVIEW_DATABASE_DRIVER: postgres
      PHOTOVIEW_POSTGRES_URL: postgresql://photoview:[REDACTED]@my.pgsql.ip/photoview 
      PHOTOVIEW_DISABLE_FACE_RECOGNITION: 1
      PHOTOVIEW_DISABLE_RAW_PROCESSING: 0
      PHOTOVIEW_DISABLE_VIDEO_ENCODING: 1
      PHOTOVIEW_LISTEN_IP: localhost
      PHOTOVIEW_LISTEN_PORT: 80
      PHOTOVIEW_MEDIA_CACHE: '/app/cache'

    volumes:
      - /sharedfolders/photoview/cache:/app/cache
      - /sharedfolders/photos:/media:ro
```

Docker logs while scanning:
```
WARN: SaveEXIF for PA272379.jpg failed: failed to parse exif data: exiftool's buffer too small (see Buffer init option)
```

Database:
```
photoview=> select exif_id,title from media where title = 'PA272379.jpg';
 exif_id |    title     
---------+--------------
         | PA272379.jpg
```
