### ISSUE TITLE
Errors in Photoview image

### ISSUE THREAD

**Issue by t18n** [photoview/photoview#862]
**Describe the bug**
When running Photoview with Docker compose, I consistantly got 2 errors "Error: failed to initialize database" and "No .env file found" is on my both Ubuntu and my Mac

yet the server still works fine and the environments are loaded properly

**To Reproduce**
Fresh install with [Photoview example](https://github.com/photoview/photoview/blob/master/docker-compose.example.yml), replace some hardcoded configs with `.env` file

**Expected behavior**
No misleading errors

**Screenshots**
![image](https://github.com/photoview/photoview/assets/14198542/772f9896-3db7-4519-b314-6849b5332fd3)

**Comment by kkovaletp** [comment]
I assume that you use .env on the docker-compose level and not mount it in a volume inside the photoview container. In that case, it is completely fine: the message tells that there is no .env file inside photoview container in the folder, where it expects to be, and photoview is going to work with env variables instead. Your .env on the host is processed by docker and converted into a set of env vars like they are part of the YAML file.

The error about init DB means that the photoview tries to connect to the DB too early: at the time, when DB is not yet ready for connections (which you could see on your screenshot - right after the error the DB container just starts the init procedure). To avoid this you need to add the healthcheck to the DB service in the compose YAML - in this way, docker will know when DB is ready, so it's time to start the dependent photoview container.

I use this healthcheck, but it is better to replace it by some SQL query to specific table of the photoview DB - then you verify not only that the DB server is up, but also the DB is mounted and ready. However, it will work only after 1st run and DB init finished successfully, while my healthcheck works for any MySQL DB:
```
     healthcheck:
       test: mysqladmin -p'photosecret' ping -s -h localhost
       interval: 1m
       timeout: 5s
       retries: 5
       start_period: 3m
```

Also, I set next healthcheck for the photoview service as well:
```
     healthcheck:
       test: [ "CMD", "bash", "-c", "[ $(curl -s -o /dev/null -w '%{http_code}' http://localhost:80/login) == '200' ]" ]
       interval: 1m
       timeout: 2s
       retries: 5
       start_period: 30s
```
