### ISSUE TITLE
Permission denied error for folders, mounted from the host to the `photoview` container (cache and media library folders)

### ISSUE THREAD

**Issue by Darkatek7** [photoview/photoview#946]
**Describe the bug**
I get this error:
2024/05/15 15:45:53 ERROR: Error scanning media for album (38) file (/photos/myfolder/theimage.jpg): cache directory error (/photos/myfolder/theimage.jpg): could not make album image cache directory: mkdir /app/cache/38: permission denied

**To Reproduce**
1. Go to 'settings'
2. Click on 'scan'
3. Wait

**Expected behavior**
Doesn't throw an exeption and creations cache directory files

**Screenshots**
![image](https://github.com/photoview/photoview/assets/50767771/28ff8fa8-0d6a-47f1-8a2f-c878a2d2cdfa)

**Your environment:**
Feel free to remove and add what you think might be useful.

 - Are you using Docker? [yes]
 - Database [mariadb 10.5]
 - Browser [brave]
 - Version [master docker image]

**Additional context**
here is my docker compose:
```
version: "3"
services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - TZ=Europe/Vienna
      - PUID=0
      - PGID=0
    volumes:
      - db_data:/var/lib/mysql
  photoview:
    image: viktorstrate/photoview:master
    restart: always
    ports:
      - 3015:80
    depends_on:
      - db
    environment:
      - PHOTOVIEW_DATABASE_DRIVER=database
      - PHOTOVIEW_MYSQL_URL=photoview:photosecret@tcp(db)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
      - TZ=Europe/Vienna
      - PUID=0
      - PGID=0
      #- PHOTOVIEW_DATABASE_DRIVER=sqlite
      #- PHOTOVIEW_SQLITE_PATH=/app/database/photoview.db
      # Optional: If you are using Samba/CIFS-Share and experience problems with "directory not found"
      # Enable the following Godebug
      # - GODEBUG=asyncpreemptoff=1


      # Optional: To enable map related features, you need to create a mapbox token.
      # A token can be generated for free here https://account.mapbox.com/access-tokens/
      # It's a good idea to limit the scope of the token to your own domain, to prevent others from using it.
      # - MAPBOX_TOKEN=<YOUR TOKEN HERE>

    volumes:
      - api_cache:/app/cache
      - /media/mount/View/Upload:/photos:ro
      - /home/user/photoview/database:/app/database
volumes:
  db_data: null
  api_cache: null
networks: {}

```
