### ISSUE TITLE
Status unauthenticated behind cloudflare tunnel and cannot play videos

### ISSUE THREAD

**Issue by Darkatek7** [photoview/photoview#966]
**Describe the bug**
I can't watch any Videos when i acces my cloudflare tunnel url, it works perfectly fine when accessing thorugh local lan

**To Reproduce**
1. Setup cloudflare tunnel
2. create cloudlfare zero trust public hostname
3. access webui through public url
4. cannot play videos and see this error in log 
![image](https://github.com/photoview/photoview/assets/50767771/dda0c828-55eb-4ac2-baf5-05410dae03cc)

**Expected behavior**
Can play the video

**Screenshots**
![image](https://github.com/photoview/photoview/assets/50767771/a294a45c-d4c2-43d6-ac41-44f887a5553b)

**Your environment:**
Docker

 - Are you using Docker? yes
 - Database mariadb lts
 - Browser Brave
 - Version viktorstrate/photoview:master

**Additional context**
My docker compose
``` 
services:
  photoview:
    image: viktorstrate/photoview:master
    hostname: photoview
    container_name: photoview
    group_add:
      - "105"
    restart: unless-stopped
    stop_grace_period: 10s
    ports:
      - 3015:80 ## HTTP port (host:container)
    depends_on:
      mariadb:
        condition: service_healthy
    ## Security options for some restricted systems
    #security_opt:
    #  - seccomp:unconfined
    #  - apparmor:unconfined
    environment:
      PHOTOVIEW_DATABASE_DRIVER: ${PHOTOVIEW_DATABASE_DRIVER}
      PHOTOVIEW_MYSQL_URL: ${MARIADB_USER}:${MARIADB_PASSWORD}@tcp(photoview-mariadb)/${MARIADB_DATABASE}sslmode=${PGSQL_SSL_MODE}
      PHOTOVIEW_LISTEN_IP: photoview
      PHOTOVIEW_MEDIA_CACHE: /home/photoview/media-cache
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro ## use local time from host
      - /etc/timezone:/etc/timezone:ro ## use timezone from host
      - ${HOST_PHOTOVIEW_LOCATION}/storage:/home/photoview/media-cache
      - ${HOST_PHOTOVIEW_MEDIA_ROOT}:/photos:ro
      - /media/Plex/View/cache:/home/photoview/media-cache

  ## Comment out the `mariadb` service if PHOTOVIEW_DATABASE_DRIVER is set to `sqlite` or `postgres` in the .env
  mariadb:
    image: mariadb:lts
    labels:
      - com.centurylinklabs.watchtower.enable=true
    hostname: photoview-mariadb
    container_name: photoview-mariadb
    restart: unless-stopped
    stop_grace_period: 5s
    ## Optimized MariaDB startup command for better performance and compatibility
    command: mariadbd --innodb-buffer-pool-size=512M
      --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci --max-connections=512
      --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    security_opt:
      ## see https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1136151239
      - seccomp:unconfined
      - apparmor:unconfined
      ## Uncomment next 2 lines if you want to access the database directly
      # ports:
      # - "3306:3306"
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      ## Example:
      ## - "/host/folder:/container/folder"
      - /etc/localtime:/etc/localtime:ro ## use local time from host
      - /etc/timezone:/etc/timezone:ro ## use timezone from host
      - /home/heel/photoview/database/mariadb:/var/lib/mysql ## DO NOT REMOVE
    healthcheck:
      test: healthcheck.sh --connect --innodb_initialized
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 3m
networks: {}

```
